// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Mgmt_System_MVC.Data;

namespace Student_Mgmt_System_MVC.Migrations
{
    [DbContext(typeof(Student_Mgmt_System_DB))]
    [Migration("20200712231054_student")]
    partial class student
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Student_Mgmt_System_MVC.Models.Course_details", b =>
                {
                    b.Property<int>("course_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("course_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.HasKey("course_ID");

                    b.ToTable("Course_details");
                });

            modelBuilder.Entity("Student_Mgmt_System_MVC.Models.Student_enrollment", b =>
                {
                    b.Property<int>("Student_Enrollment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Course_Detailscourse_ID")
                        .HasColumnType("int");

                    b.Property<int>("course_ID")
                        .HasColumnType("int");

                    b.Property<int?>("student_Detailsstudent_ID")
                        .HasColumnType("int");

                    b.Property<int>("student_ID")
                        .HasColumnType("int");

                    b.Property<int?>("tutor_Detailstutor_ID")
                        .HasColumnType("int");

                    b.Property<int>("tutor_ID")
                        .HasColumnType("int");

                    b.HasKey("Student_Enrollment_ID");

                    b.HasIndex("Course_Detailscourse_ID");

                    b.HasIndex("student_Detailsstudent_ID");

                    b.HasIndex("tutor_Detailstutor_ID");

                    b.ToTable("Student_enrollment");
                });

            modelBuilder.Entity("Student_Mgmt_System_MVC.Models.Tutor_details", b =>
                {
                    b.Property<int>("tutor_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("tutor_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tutor_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tutor_ID");

                    b.ToTable("Tutor_details");
                });

            modelBuilder.Entity("Student_Mgmt_System_MVC.Models.student_Details", b =>
                {
                    b.Property<int>("student_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("student_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_ID");

                    b.ToTable("student_Details");
                });

            modelBuilder.Entity("Student_Mgmt_System_MVC.Models.Student_enrollment", b =>
                {
                    b.HasOne("Student_Mgmt_System_MVC.Models.Course_details", "Course_Details")
                        .WithMany()
                        .HasForeignKey("Course_Detailscourse_ID");

                    b.HasOne("Student_Mgmt_System_MVC.Models.student_Details", "student_Details")
                        .WithMany()
                        .HasForeignKey("student_Detailsstudent_ID");

                    b.HasOne("Student_Mgmt_System_MVC.Models.Tutor_details", "tutor_Details")
                        .WithMany()
                        .HasForeignKey("tutor_Detailstutor_ID");
                });
#pragma warning restore 612, 618
        }
    }
}
